version: "3.7"

services:

  database:
    image: postgres
    container_name: database_cars_marketplace
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=cars
      - POSTGRES_DB=cars_marketplace
    volumes:
      - pgdata:/data/postgres
    # network_mode: host

  app:
    build: .
    container_name: api_cars
    ports: 
      - 3333
    volumes:
      - .:/usr/app
      # - /usr/app/node_modules
    # network_mode: host

volumes:
  pgdata:
    driver: local
# docker rm $(docker ps -qa)
# docker image rm $(docker image ls -qa)